### ISSUE TITLE
Digital Clock value won't reset after {model}_initialize is called.

### ISSUE THREAD

**Issue by kllmagn** [dapperfu/Python-Simulink#1]
Digital Clock value stays the same even after initialization function is called. Other signals reset, but always to their 1st step values (not 0th). All signals have same values for 0th and 1st step. What can be a problem here?

**Comment by dapperfu** [comment]
I'm not longer at my last position with a matlab licence. Since this is coming from the DLL it may be worth pinging yoru Mathworks representative to see if there is a reason this happens.
